title:               Daniele Zambon
url:                 https://dzambon.github.io
baseurl:             ""
google_analytics_tag: 'UA-119549040-1'

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle', 'TODO.md', 'blog']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  givenname:         Daniele
  lastname:          Zambon
  name:              Daniele Zambon
  url:               dzambon.github.io
  email:             daniele.zambon@usi.ch
  github:            dzambon
  orcid:             0000-0003-3722-9784
  google_scholar:    JaQGQEwAAAAJ&hl
  linkedin:          danielezambon
  twitter:           "dan_zambon"


plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
