title:               Daniele Zambon
url:                 https://dzambon.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Daniele Zambon 
  url:               dzambon.github.io
  email:             daniele.zambon@usi.ch
  github:            https://github.com/dzambon
  google_scholar:    https://orcid.org/0000-0003-3722-9784 
  orcid:             https://scholar.google.ch/citations?user=JaQGQEwAAAAJ&hl=en&oi=ao


plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist